#!/bin/bash

echo "Installing virtualbox, for Linux only"

YUM_CMD=$(command -v yum)
APT_GET_CMD=$(command -v apt-get)

if [[ ! -z $YUM_CMD ]]; then
    # for virtualbox kernel module loading
    sudo yum install kernel-devel-$(uname -r)
    sudo yum install virtualbox

elif [[ ! -z $APT_GET_CMD ]]; then
    sudo apt-get install linux-headers-$(uname -r)
    sudo apt-get install virtualbox
fi
